name: API-Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: gen-protoc
      name: Generate protoc
      run: ./api/gen_protoc.sh

    - id: run-docker-compose
      name: Run docker compose
      run: docker compose up -d --build --wait

    - id: uploader
      run: go test .
      working-directory: ./uploader

    - id: database-test
      name: Database test
      run: go test .
      working-directory: ./database

    - id: api-test
      name: Api test
      run: go test .
      working-directory: ./api
