name: Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      problems-branch:
        type: string
        default: master
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        description: environment of deploy
      problems-branch:
        type: string
        default: master
        description: branch of library-checker-problems

jobs:
  api-deploy:
    uses: ./.github/workflows/api-deploy.yml
    with:
      env: ${{ inputs.env }}

  problems-deploy:
    needs: api-deploy
    uses: ./.github/workflows/problems-deploy.yml
    with:
      env: ${{ inputs.env }}
      problems-branch: ${{ inputs.problems-branch }}

  judge-deploy:
    needs: problems-deploy
    uses: ./.github/workflows/judge-deploy.yml
    with:
      env: ${{ inputs.env }}
