name: Judge-Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      build-base:
        type: boolean
        required: false
        default: true
      test-created-image:
        type: boolean
        required: false
        default: true
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        description: deployment target environment
      build-base:
        type: boolean
        default: true
        description: build base image or not
      test-created-image:
        type: boolean
        default: true
        description: whether test created judge image or not

jobs:
  image-build:
    uses: ./.github/workflows/judge-image-build.yml
    with:
      env: ${{ inputs.env }}
      build-base: ${{ inputs.build-base }}
      test-created-image: ${{ inputs.test-created-image }}

  deploy:
    if: success() || !inputs.image_build
    needs: [image-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: gce-judge-deployer@library-checker-project.iam.gserviceaccount.com
          token_format: access_token

      - id: setup-cloud-sdk
        name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - id: instance-template-name
        name: Generate instance template name
        run: echo "::set-output name=name::${{ inputs.env }}-judge-template-$(date +'%Y-%m-%d-%H-%M-%S')"

      - id: create-judge-template
        name: Create judge template
        run: >
          gcloud compute instance-templates create ${{ steps.instance-template-name.outputs.name }}
          --preemptible
          --machine-type c2-standard-4
          --image-family v1-${{ inputs.env }}-judge-image
          --service-account gce-judge@library-checker-project.iam.gserviceaccount.com
          --scopes default,cloud-platform
          --boot-disk-size 50GB
          --metadata env=${{ inputs.env }}

      - id: update-instance-group
        name: Update instance group
        run: >
          gcloud compute instance-groups managed rolling-action
          start-update ${{ inputs.env }}-judge-instance-group
          --region asia-northeast1
          --version=template=${{ steps.instance-template-name.outputs.name }}
