name: Prod-Problems-Deploy

on:
  repository_dispatch:
    types: [prod-problems-deploy]
  workflow_call:

jobs:
  problems-deploy:
    uses: ./.github/workflows/problems-deploy.yml
    secrets: inherit
    with:
      env: prod
