name: API-Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: test
      run: go test .
